apiVersion: v1
kind: ConfigMap
metadata:
  name: mining-management-web-config
data:
  config.json: |
    {
      "apiUrl": "/api",
      "production": false,
      "appTitle": "Mining Management System"
    }
